apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: {name: ncpconfigs.nsx.vmware.com}
spec:
  group: nsx.vmware.com
  names:
    kind: NCPConfig
    plural: ncpconfigs
    shortNames: [ncpcfg]
    singular: ncpconfig
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema: {type: object, x-kubernetes-preserve-unknown-fields: true}
    served: true
    storage: true
