apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: {name: nsxlocks.nsx.vmware.com}
spec:
  group: nsx.vmware.com
  names:
    kind: NSXLock
    plural: nsxlocks
    shortNames: [nsxlo]
    singular: nsxlock
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema: {type: object, x-kubernetes-preserve-unknown-fields: true}
    served: true
    storage: true
