name: Build image

on:
  pull_request:
    branches:
      - master

jobs:
  build-image:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check-out code
        uses: actions/checkout@v2
      - name: Build image
        run: make

